In [1]:
import pandas as pd
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import numpy as np

from pydataset import data

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
dftrain= pd.read_csv('dftrain.csv')

In [3]:
dfscore= dftrain[['Pitch_Type','ball_count', 'strike_count', 'on_1b', 'on_2b', 'on_3b', 'run_difference']]

In [4]:
#Split Data
X= dfscore[['ball_count', 'strike_count', 'on_1b', 'on_2b', 'on_3b', 'run_difference']]
y=dfscore['Pitch_Type']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)

X_train.head()

ball_count  strike_count  on_1b  on_2b  on_3b  run_difference
780086            3             2      1      1      0              -1
578325            0             1      0      0      0              -2
705263            2             1      0      0      0               4
1047168           1             0      0      0      0               1
1212563           1             1      0      0      0               1

In [5]:
#Train Model

#Create the Decision Tree Object

# for classification you can change the algorithm to gini or entropy (information gain).  Default is gini.
clf = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=123, )

In [6]:
#Fit the model to the training data

clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [7]:
#guess pitch

y_pred = clf.predict(X_train)
y_pred[0:5]

array([1, 1, 1, 1, 1])

In [8]:
#Estimate the probability of a pitch type

y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.58533716, 0.1169134 , 0.29774944],
       [0.50013985, 0.14566435, 0.3541958 ],
       [0.50013985, 0.14566435, 0.3541958 ],
       ...,
       [0.50013985, 0.14566435, 0.3541958 ],
       [0.45459156, 0.13010126, 0.41530718],
       [0.58533716, 0.1169134 , 0.29774944]])

In [9]:
#Accuracy: number of correct predictions over the number of total instances that have been evaluated.

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.53


In [10]:
confusion_matrix(y_train, y_pred)

array([[519013,      0,      0],
       [117504,      0,      0],
       [343715,      0,      0]])

In [12]:
import pandas as pd

labels = sorted(y_train.unique())

pd.DataFrame(confusion_matrix(y_train, y_pred), index=labels, columns=labels)


1  2  3
1  519013  0  0
2  117504  0  0
3  343715  0  0

In [13]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.53      1.00      0.69    519013
           2       0.00      0.00      0.00    117504
           3       0.00      0.00      0.00    343715

    accuracy                           0.53    980232
   macro avg       0.18      0.33      0.23    980232
weighted avg       0.28      0.53      0.37    980232



In [14]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.53
