In [116]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import numpy as np 

import numpy as np 
import scipy as sp 
import sklearn
import random 
import time 

from sklearn import preprocessing, model_selection
from sklearn.model_selection import train_test_split

from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical
from sklearn.utils import shuffle

In [106]:
df=pd.read_csv('OHtop50.csv')


In [107]:
df=df.drop(columns='Unnamed: 0')
df.head()

Pitch_Type  inning  run_difference  ball_count  strike_count  outs  \
0           1       1               0           0             0     0   
1           1       1               0           0             1     0   
2           1       1               0           0             2     0   
3           1       1               0           0             2     0   
4           3       1               0           1             2     0   

   pitch_num_ab  on_1b  on_2b  on_3b  ...  Pitcher_name_Mike Leake  \
0             1      0      0      0  ...                        0   
1             2      0      0      0  ...                        0   
2             3      0      0      0  ...                        0   
3             4      0      0      0  ...                        0   
4             5      0      0      0  ...                        0   

   Pitcher_name_Rick Porcello  Pitcher_name_Robbie Ray  \
0                           0                        0   
1                           0                        0   
2                           0                        0   
3                           0                        0   
4                           0                        0   

   Pitcher_name_Sonny Gray  Pitcher_name_Taijuan Walker  \
0                        0                            0   
1                        0                            0   
2                        0                            0   
3                        0                            0   
4                        0                            0   

   Pitcher_name_Tanner Roark  Pitcher_name_Trevor Bauer  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   Pitcher_name_Ubaldo Jimenez  Pitcher_name_Wade Miley  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   

   Pitcher_name_Zack Greinke  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 61 columns]

In [123]:
X = df.drop(['Pitch_Type'], axis = 1)
X = np.array(X)
y = df['Pitch_Type']
y.head()

0    1
1    1
2    1
3    1
4    3
Name: Pitch_Type, dtype: int64

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [125]:
#Since our input features are at different scales we need to standardize the input.
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-1.35123217, -0.20742538, -0.9069913 , ..., -0.13775705,
        -0.1462847 , -0.1460858 ],
       [-1.35123217, -0.20742538, -0.9069913 , ..., -0.13775705,
        -0.1462847 , -0.1460858 ],
       [-1.35123217, -0.20742538, -0.9069913 , ..., -0.13775705,
        -0.1462847 , -0.1460858 ],
       ...,
       [ 0.68350967, -0.20742538,  1.17250668, ..., -0.13775705,
        -0.1462847 , -0.1460858 ],
       [ 0.68350967, -0.20742538,  2.21225566, ..., -0.13775705,
        -0.1462847 , -0.1460858 ],
       [ 0.68350967, -0.20742538, -0.9069913 , ..., -0.13775705,
        -0.1462847 , -0.1460858 ]])

In [147]:
#Split Data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [148]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(11, activation='relu', kernel_initializer='random_normal', input_dim=60))

In [149]:
#Second  Hidden Layer
classifier.add(Dense(11, activation='relu', kernel_initializer='random_normal'))

In [150]:
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [151]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [ ]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, epochs=10)

Epoch 1/10
516651/516651 [==============================] - 45s 87us/step - loss: -12.1815 - acc: 0.5475
Epoch 2/10
516651/516651 [==============================] - 46s 90us/step - loss: -12.3456 - acc: 0.5476
Epoch 3/10
516651/516651 [==============================] - 46s 89us/step - loss: -12.3456 - acc: 0.5476
Epoch 4/10
313664/516651 [=================>............] - ETA: 18s - loss: -12.3416 - acc: 0.5479

In [144]:
eval_model=classifier.evaluate(X_train, y_train)
eval_model

459245/459245 [==============================] - 14s 30us/step


[-12.331643273386044, 0.5480124987758125]

In [145]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

In [146]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[62784     0     0]
 [14961     0     0]
 [37067     0     0]]
